name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install pandoc
      run: sudo apt-get install -y pandoc
    - name: Install pandoc citeproc
      run: sudo apt-get install -y pandoc-citeproc
    - name: Compile all and produce *.docx, *.pdf, and *.html files
      run: ./compileAll.sh
